export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const INCREMENT_CART_ITEMS = 'INCREMENT_CART_ITEMS';
export const DECREMENT_CART_ITEMS = 'DECREMENT_CART_ITEMS';
